src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 * fields={"email"},
 * message= "L'email que vous avez indiqué est déjà utilisé !" )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $NumCom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="6", minMessage="Votre mot de passe doit faire minimum 6 caractères")
     *  @Assert\EqualTo(propertyPath="Confir_pwd", message="Vous n'avez pas tapé le même mot de passe")
     */
    private $Password;

     /**
     * @Assert\EqualTo(propertyPath="Password", message="Vous n'avez pas tapé le même mot de passe")
     */
    public $Confir_pwd;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->sitUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getNumCom(): ?string
    {
        return $this->NumCom;
    }

    public function setNumCom(string $NumCom): self
    {
        $this->NumCom = $NumCom;

        return $this;
    }

     /**
     * @see UserInterface
     */
    public function getRoles(): array
    {

          // guarantee every user at least has ROLE_USER
          $roles[] = 'ROLE_USER';

          return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function getUserIdentier(): ?string
    {
        return $this->email;
    }
    

    public function eraseCredentials()
    {
       
    }
    public function getSalt()
    {
        
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/accueil ", name="home")
     */
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base_admin.html.twig' %}
{% block title %}Accueil{% endblock %}
{% block body %}
{% include 'partials/header.html.twig' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row">
                    <div class="col">
                        <ol class="breadcrumb d-flex align-items-center">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">IPdemat</a></li>
                            <li class="breadcrumb-item active">Accueil</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="banner d-flex justify-content-between align-items-start p-3">
        <div class="text-white">
            <div>
                <h2 class="text-white">Bienvenue sur
                    <span class="text-success">IPDemat</span>
                    <span class="text-danger"> - One</span>
                    {{ app.user ? app.user.prenom : "" }}</h2>
            </div>
        </div>
        <div class="input-rounded">
            <i class="fas fa-search text-white"></i>
            <input type="search" placeholder="Rechercher">
        </div>
    </div>

    <div class="card-statistic-simple-user">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-12 margin-top-30 margin-left-20 card-statistic-item">
                    <i class="fas fa-dollar-sign text-white"></i>
                        {# {% set recu = 0 %}
                        {% set depense = 0 %}

                        {% if recu > 0 %} #}
                        <span class="text-white mx-2">Crédit</span>
                        <span class="text-white">2</span>
                        {# {% endif %} #}
                    
                </div>
                <div class="col-lg-3 col-sm-12 margin-top-30 margin-left-20 card-statistic-item">
                    <i class="fas fa-dollar-sign text-white"></i>
                    <span class="text-white mx-2">Dédit</span>
                    <span class="text-white">56</span>
                </div>
                <div class="col-lg-3 col-sm-12 margin-top-30 margin-left-20 card-statistic-item">
                    <i class="fas fa-hands-helping text-white"></i>
                    <span class="text-white mx-2">Partenaire</span>
                    <span class="text-white">56</span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}