src/Entity/Part.php
<?php

namespace App\Entity;

use App\Repository\PartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PartRepository::class)
 */
class Part
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Num;

    /**
     * @ORM\OneToMany(targetEntity=Recu::class, mappedBy="client")
     */
    private $recus;

    public function __construct()
    {
        $this->recus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getNum(): ?string
    {
        return $this->Num;
    }

    public function setNum(string $Num): self
    {
        $this->Num = $Num;

        return $this;
    }

    /**
     * @return Collection|Recu[]
     */
    public function getRecus(): Collection
    {
        return $this->recus;
    }

    public function addRecu(Recu $recu): self
    {
        if (!$this->recus->contains($recu)) {
            $this->recus[] = $recu;
            $recu->setClient($this);
        }

        return $this;
    }

    public function removeRecu(Recu $recu): self
    {
        if ($this->recus->removeElement($recu)) {
            // set the owning side to null (unless already changed)
            if ($recu->getClient() === $this) {
                $recu->setClient(null);
            }
        }

        return $this;
    }

}

src/Entity/PartType.php
<?php

namespace App\Form;

use App\Entity\Part;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class PartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Num',TextType::class,[
                'label'=> 'Numéro'
            ])
            ->add('Nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Part::class,
        ]);
    }
}

src/Form/PartType.php
<?php

namespace App\Form;

use App\Entity\Part;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class PartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Num',TextType::class,[
                'label'=> 'Numéro'
            ])
            ->add('Nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Part::class,
        ]);
    }
}

src/Controller/PartController.php
<?php

namespace App\Controller;

use App\Entity\Part;
use App\Form\PartType;
use App\Repository\PartRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PartController extends AbstractController
{
    /**
     * @Route("/partenaire", name="part")
     */
    public function index(PartRepository $partRepository): Response
    {
        return $this->render('part/index.html.twig', [
            'parts' => $partRepository->findAll(),
        ]);
    }

    /**
     * @Route("/ajout-part", name="part_new")
     */
    public function create(Request $request, EntityManagerInterface $manager)
    {   
        $part = new Part();
        $form = $this->createForm(PartType::class, $part);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($part);
            $manager->flush();

            return $this->redirectToRoute("part");
        }
                
        return $this->render("part/add.html.twig",[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="part_edit")
     */
    public function edit(Request $request, EntityManagerInterface $manager,Part $part){
        $form = $this->createForm(PartType::class, $part);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($part);
            $manager->flush();

            return $this->redirectToRoute("part");
        }

        return $this->render("part/add.html.twig",[
            'form' => $form->createView()
        ]);
    } 

    /**
     * @Route("/{id}/delete", name="part_suppr")
     */
    public function delete(EntityManagerInterface $manager,Part $part)
    {
        $manager->remove($part);
        $manager->flush();

        return $this->redirectToRoute('part');
    }
}

templates/part/add.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container bootstrap snippet">
    <h1>Ajouter un partenaire</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="flex">
        <button class="btn btn-success">Enregitrer</button>
        <a href="{{ path('part') }}" class="btn btn-warning rounded-0">
            Retourner
        </a>
    </div>
    {{ form_end(form) }}
</div>
{% endblock %}

templates/part/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}partenaire{% endblock %}

{% block body %}
{% include 'partials/header.html.twig' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row">
                    <div class="col">
                        <ol class="breadcrumb pt-3 d-flex align-items-center">
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0);">IPDemat</a>
                            </li>
                            <li class="breadcrumb-item active">Mes partenaires</li>
                        </ol>
                    </div>
                </div>
                <div class="col-auto align-self-center">
                    <a href="{{ path('part_new') }}" class="btn btn-primary float-right mb-3"><i class="fa fa-plus"></i>Ajouter</a>
                    {% include "partials/research.html.twig" %}
                </div>

            </div>
            <table class="table table-striped" id="table">
                <thead>
                    <tr>
                        <td class="text-white">Nom</td>
                        <td class="text-white">Numéro</td>
                        <td class="text-white"></td>
                    </tr>
                </thead>
                <tbody>
                    {% for part in parts %}
                    <tr>
                        <td>{{ part.nom }}</td>
                        <td>{{ part.num }}</td>
                        <td>
                            <div class="dropdown show">
                                <a class="btn btn-secondary dropdown-toggle" role="button" id="dropdownMenuLink"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    Action
                                </a>

                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="{{ path('part_edit',{id:part.id}) }}">Mettre à jour
                                    </a>
                                    <a class="dropdown-item" href="{{ path('part_suppr',{id:part.id}) }}">Suppression</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- </div> -->
        </div>
    </div>
</div>
{% endblock %}