src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 * fields={"email"},
 * message= "L'email que vous avez indiqué est déjà utilisé !" )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $NumCom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="6", minMessage="Votre mot de passe doit faire minimum 6 caractères")
     *  @Assert\EqualTo(propertyPath="Confir_pwd", message="Vous n'avez pas tapé le même mot de passe")
     */
    private $Password;

     /**
     * @Assert\EqualTo(propertyPath="Password", message="Vous n'avez pas tapé le même mot de passe")
     */
    public $Confir_pwd;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->sitUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getNumCom(): ?string
    {
        return $this->NumCom;
    }

    public function setNumCom(string $NumCom): self
    {
        $this->NumCom = $NumCom;

        return $this;
    }

     /**
     * @see UserInterface
     */
    public function getRoles(): array
    {

          // guarantee every user at least has ROLE_USER
          $roles[] = 'ROLE_USER';

          return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function getUserIdentier(): ?string
    {
        return $this->email;
    }
    

    public function eraseCredentials()
    {
       
    }
    public function getSalt()
    {
        
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Controller/MemberArea/UserController.php
<?php

namespace App\Controller\MemberArea;

use App\Entity\User;
use App\Form\RegistrationType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/utilisateur", name="user")
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/ajout-utilisateur", name="inscription")
     */
    public function incription(Request $request, EntityManagerInterface $manager,UserPasswordEncoderInterface $encoder)
    {

        $user = new User();
        $form = $this->createForm(RegistrationType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $manager->persist($user);
            $manager-> flush();
            $this->addFlash(
                'success',
                "L’<strong>utilisateur</strong> a été bien enregistrer"
            );
            return $this->redirectToRoute('user');
        }
        return $this->render('security/inscr.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/profile", name="profile")
     */
    public function profil(User $user)
    {
        return $this->render('security/profil.html.twig',[
            'users'=>$userRepository->findBy()
        ]);
    }

    /**
     * @Route("/{id}/edite-le-role d'utilisateur", name="edite_user")
     */
    public function editer(Request $request, EntityManagerInterface $manager,UserPasswordEncoderInterface $encoder,User $user)
    {
        $form = $this->createForm(RegistrationType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $manager->persist($user);
            $manager-> flush();

            return $this->redirectToRoute('user');
        }
        return $this->render('user/edit.html.twig',[
            'form' => $form->createView()
        ]);
}

    // /**
    //  * @Route("/{id}/user-delete", name="user_delete")
    //  */
    // public function delete(EntityManagerInterface $manager, User $user)
    // {
    //     $manager->remove($user);
    //     $manager->flush();

    //     return $this->redirectToRoute("user");
    // }
}

templates/user/edit.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Modification d'utilisateur{% endblock %}

{% block body %}
{% include 'partials/header.html.twig' %}
<div class="container bootstrap snippet">

    <div class="container mt-4">
        <h4>Modifier utilisateur</h4>
        {{ form_start(form) }}

        <div>
            <img src="{{ asset('img/no-image.png') }}" class="avatar avatar-preview" alt="avatar">
            <div class="row">
                <div class="col-md-5">{{ form_row(form.picture) }}</div>
            </div>
        </div>
        </hr><br>

        <div class="row">
            <div class="col-md-5">{{ form_row(form.Nom) }}</div>
            <div class="col-md-5">{{ form_row(form.Prenom) }}</div>
        </div>

        <div class="row center">
            <div class="col-md-3">{{ form_row(form.NumCom) }} </div>
            <div class="col-md-3">{{ form_row(form.Tel) }}</div>
        </div>

        <div class="row">
            <div class="col-md-5">{{ form_row(form.email) }}</div>
        </div>

        <div class="row">
            <div class="col-md-5">{{ form_row(form.Password) }}</div>
            <div class="col-md-5">{{ form_row(form.Confir_pwd) }}</div>
        </div>

        <div class="flex float-right">
            <Button class="btn btn-success">Modifier</Button>
            <a href="{{path('user')}}" class="btn btn-warning rounded-0">
                Annuler
            </a>
        </div>
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script src="{{ asset('js/preview-upload.js') }}"></script>
{% endblock %}

templates/user/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %} listes des utilisateur{% endblock %}

{% block body %}
{% include 'partials/header.html.twig' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row">
                    <div class="col">
                        <ol class="breadcrumb pt-3 d-flex align-items-center">
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0);">IPDemat</a>
                            </li>
                            <li class="breadcrumb-item active">Utilisateur</li>
                        </ol>
                    </div>
                </div>
                <div class="col-auto align-self-center">
                    <a href="{{url('inscription')}}" class="btn btn-primary float-right mb-3">
                        <i class="fa fa-plus"></i>
                        Créer un agent
                    </a>
                    {% include "partials/research.html.twig" %}
                </div>
            </div>
            <table class="table table-striped" id="table">
                <thead>
                    <tr>
                        <td class="text-white">Numéro de compte</td>
                        <td class="text-white">Nom</td>
                        <td class="text-white">Prénom</td>
                        <td class="text-white">Téléphone</td>
                        <td class="text-white">Email</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.NumCom }}</td>
                        <td>{{ user.Nom }}</td>
                        <td>{{ user.Prenom }}</td>
                        <td>{{ user.tel }}</td>
                        <td>{{ user.email }}</td>
                        <td>
                            <a href="{{ path('edite_user', {id:user.id}) }}">
                                <i class="fas fa-edit text-info"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}